### ISSUE TITLE
Editing template files w/ Docker for Mac

### ISSUE THREAD

**Issue by shanebonham** [wyveo/craftcms-docker#19]
Hi, sorry for the newbie question, but the instructions here https://github.com/wyveo/craftcms-docker#editing-craftcms-files don't seem to apply to Docker for Mac (`/var/lib/docker` isn't a directory). Is there a way to edit templates using Docker for Mac?

**Comment by colinwilson** [comment]
As far as I know Docker for Mac uses a Linux VM created by HyperKit for storing and running containers on Mac. You need to open a shell to the VM and then navigate to the intended directory.

Try:
```
$ sudo screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
$ cd /var/lib/docker/volumes/craftcmsdocker_craftcms-data/_data
```

**Comment by shanebonham** [comment]
That works, but doesn't help much for editing templates. I tried mounting `/usr/share/nginx` to a local directory, which seems to work for `/var/log`, and works for a Wordpress container I was using, but doesn't seem to work here.

----

Update: It seems the `/usr/share/nginx` because mounting as a local volume nukes it and replaces it. That is, if I ssh into the container and run `composer create-project craftcms/craft /usr/share/nginx/`, then the files start to appear locally (though I still can't actually get Craft running like that).

----

(I realize none of this is the fault of this repo, I'm mostly documenting it in case it helps someone else.)

**Comment by colinwilson** [comment]
I don't have a lot of experience with Docker for Mac. How are you mounting the directories?

**Comment by shanebonham** [comment]
In `docker-compose.yml`:

```yml
...

volumes:
  # craftcms-data:
  postgresql-data:
  # craftcms-logs:

services:
    web:
      image: wyveo/craftcms-docker:latest
      ports:
        - 80:80
      volumes:
        # - craftcms-logs:/var/log
        # - craftcms-data:/usr/share/nginx
        - ./craftcms-logs:/var/log
        - ./craftcms-data:/usr/share/nginx
...
```

From what I can tell, doing that clobbers whatever was set up in the Dockerfile for the image in that directory.
